export const actionTypes = {
    //Movies
    SET_MOVIES: 'SET_MOVIES',
    UPDATE_LIKE: 'UPDATE_LIKE',

    //
    ADD_USER: 'ADD_USER',
    UPDATE_SIGNIN_STATUS: 'UPDATE_SIGNIN_STATUS',
    UPDATE_AUTH_TOKEN: 'UPDATE_AUTH_TOKEN',

    //Splash
    UPDATE_SPLASH: 'UPDATE_SPLASH',
}